
###服务器端口号
server:
  port: 8081
###dubbo 注册到到注册中心名称
dubbo:
  application:
    name: member
  ###采用协议协议方式和端口号  
  protocol:
  ###采用dubbo协议
    name: dubbo
  ###发布dubbo端口号为20880  
    port: 20881
  registry:
  ###dubbo 注册中心地址
    address: zookeeper://127.0.0.1:2181
